### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by dudi2022** [marco-svitol/quaestio-fe#22]
Hi Marco,

I hope you are well!

I'm trying to demo the site but am getting an error 500 from the backend.

Has something changed? Could we have some test data that I can use?

I also have a question, because I am thinking about applying for new teaching jobs. Based on our work so far together, do you think it would be possible for me at this stage/what steps do you think I would need to take to be able to apply for FrontEnd dev jobs?

Wishing you all the very best!

Ciao!

Will

**Comment by marco-svitol** [comment]
hi Will.
Fine thanks! 
Try with this new URL:
https://quaestio.ilciclaio.it
If It doesn t work let me know.

I think you gained some knowledge in front end developing and what I see as peculiar positive aspect of yours is the passion and commitment you have for this tech subject.
To apply for a job I think you need a bit more of expertise.
You have all the potentials and some more experience, solving different scenario, would give you the robustness of starting a job that will introduce deadlines, customer's strict requirements and so on.

On Wednesday we will present our prototype to Guido and ask him, first of all his willing to proceed and second some reward for what we have done.
As I promised you, we will share what we will gain for the work we completed and, if you want, we will work together for the final product that would include: 
- an authentication solution/page with credentials, token, refresh token for the API calls
- more API calls to fill in the combo box by retrieving those values from the backend instead of having those hard coded (bad practice)
- improve the graphic quality

We will arrange a talk after Wednesday to discuss our next steps if you want.

**Comment by dudi2022** [comment]
Ciao Marco,

Thank you so much for your feedback! I really appreciate your professional advice about the career side.

That sounds brilliant about showing the prototype to Guido, I hope that he likes it. 

Yes, I really enjoyed working on the project so far and would be 100% ready to do the authentication/refresh tokens/other API calls and graphics if we continue with the next steps.

Let me know after Wednesday and I look forward to talking more about everything.

Wishing you all the best, passa un bel weekend!

**Comment by dudi2022** [comment]
P.S. the call issue was resolved on the main site, so I could test the project again this afternoon :-)

**Comment by marco-svitol** [comment]
Hi Will. 
Good news.
The demo with Guido went very well and we have the go to proceed!
With my friend Fabrizio we are preparing an offer.
As soon as Guido accepts we will start the development.
I will present you the new features in depth afterwards, that are more or less the ones I told you already. 
Happy to keep you onboard and it could be a nice opportunity for you to learn and improve your skill.
ciao!
Marco

**Comment by dudi2022** [comment]
Hi Marco,
This is fantastic news! I'm really happy to hear about it.
I'm really excited to keep working on it and to learn more!
Ciao and wishing you a great day,
Will
