### ISSUE TITLE
demo feedback

### ISSUE THREAD

**Issue by dudi2022** [marco-svitol/quaestio-fe#66]
Suggestions:
Give option for OPS link outside of modal - discuss
Give option for search within table - solved through testo
Review testo field and checkbox - solved

**Comment by dudi2022** [comment]
Sure!

I’m so sleepy today… but am free all weekend to discuss and make updates. I
also want to solve the responsiveness once and for all!

Just let me know when you are available!

**Comment by marco-svitol** [comment]
Hi Will,
as you may have seen I have added some issues.

Regarding your questions:

> What do you think about having an option for the link outside of the modal?

Would be nice, but we cannot present to the user a direct link to OPS anymore, because we can't track the status of the doc in such way. If we want to add a direct OPS link outide the modal we should find a solution in order to set the correct status.

> And how about having a more clear "search" option for the table 

Don't know if I got it. You want to introduce a sort of "local" search to perform a search on the results?

We can have a call on this.

ciaooooo

**Comment by dudi2022** [comment]
Ciaoooo Marco thanks for the issues!

I will work on them today and tomorrow and if you’re free let’s have a
brief call to discuss between 10-13 👌🔥
